Repository prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE, pull requests merged in 2023-10, with the labels that each got.

#6 fix: EoF 추가
  one-day-hero/.husky/pre-commit
Labels: Small Ticket

#12 기본 페이지 틀 생성했습니다.
  one-day-hero/src/app/globals.css
  one-day-hero/src/app/mission/create/page.tsx
  one-day-hero/src/app/mission/detail/[slug]/page.tsx
  one-day-hero/src/app/mission/list/layout.tsx
  one-day-hero/src/app/mission/list/ongoing/page.tsx
  one-day-hero/src/app/mission/list/suggested/page.tsx
  one-day-hero/src/app/page.tsx
Labels: 기능

#18 13 버튼
  one-day-hero/src/components/common/Button.tsx
Labels: Small Ticket, 기능

#20 라벨 컴포넌트 생성했습니다.
  one-day-hero/src/app/components/common/Label.tsx
  one-day-hero/src/app/page.tsx
Labels: 기능

#24 라벨 컴포넌트 파일 위치 변경 합니다.
  one-day-hero/src/components/common/Label.tsx
Labels: 긴급

#25 하단 nav 바
  one-day-hero/package-lock.json
  one-day-hero/package.json
  one-day-hero/src/app/page.tsx
  one-day-hero/src/components/common/BottomNav.tsx
  one-day-hero/src/components/common/IconGroup.tsx
Labels: Small Ticket, 기능

#27 요일 버튼과 요일 전체 컴포넌트
  one-day-hero/src/components/common/Day/DayButton.tsx
  one-day-hero/src/components/common/Day/DayList.tsx
  one-day-hero/src/components/common/Label.tsx
Labels: Small Ticket, 기능

#30 11 route handler에 mock 데이터 설정
  one-day-hero/src/app/api/mock/missions/route.ts
  one-day-hero/src/app/layout.tsx
  one-day-hero/src/services/missions.ts
  one-day-hero/src/services/urls.ts
  one-day-hero/tailwind.config.ts
Labels: Small Ticket

#34 31 tailwind 색상 팔레트 생성
  one-day-hero/src/app/layout.tsx
  one-day-hero/src/app/page.tsx
  one-day-hero/src/components/common/BottomNav.tsx
  one-day-hero/src/components/common/Button.tsx
  one-day-hero/src/components/common/Day/DayButton.tsx
  one-day-hero/src/components/common/Label.tsx
  one-day-hero/tailwind.config.ts
Labels: Small Ticket, 스타일

#32 26 미션 목록 아이템
  one-day-hero/public/smiling-face.png
  one-day-hero/src/app/page.tsx
  one-day-hero/src/components/common/MissionListItem.tsx
  one-day-hero/tsconfig.json
Labels: Small Ticket, 기능

#38 37 import 순서 정렬 안되는 문제
  one-day-hero/.eslintrc.json
  one-day-hero/package-lock.json
  one-day-hero/package.json
  one-day-hero/src/components/common/BottomNav.tsx
Labels: 긴급

#41 헤더 컴포넌트 생성합니다
  one-day-hero/src/components/common/DayList.tsx
  one-day-hero/src/components/common/Header.tsx
  one-day-hero/src/components/common/ToggleButton.tsx
Labels: Small Ticket

#43 미션 인포
  one-day-hero/src/app/page.tsx
  one-day-hero/src/components/common/IconGroup.tsx
  one-day-hero/src/components/common/MissionInfo.tsx
  one-day-hero/src/components/common/MissionListItem.tsx
Labels: Small Ticket, 기능

#44 39 히어로 지수
  one-day-hero/src/app/page.tsx
  one-day-hero/src/components/common/HeroScore.tsx
  one-day-hero/tailwind.config.ts
Labels: Small Ticket, 기능

#45 홈 화면 전용 헤더
  one-day-hero/public/images/원데히로고 2.png
  one-day-hero/src/app/page.tsx
  one-day-hero/src/components/common/HomeHeader.tsx
Labels: Small Ticket, 기능

#46 미션 진행 탭 컴포넌트 구현합니다
  one-day-hero/src/app/page.tsx
  one-day-hero/src/components/common/MissionProgressBar.tsx
Labels: Small Ticket, 기능

#49 탭 컴포넌트 구현
  one-day-hero/src/components/common/Tabs.tsx
Labels: Small Ticket, 기능

#51 Footer로 변경 및 스타일 수정
  one-day-hero/src/app/page.tsx
  one-day-hero/src/components/common/BottomNav.tsx
  one-day-hero/src/components/common/Footer.tsx
Labels: Small Ticket, 기능, 스타일

#54 전체 페이지 공통 스타일
  one-day-hero/src/app/(home)/layout.tsx
  one-day-hero/src/app/(home)/page.tsx
  one-day-hero/src/app/globals.css
  one-day-hero/src/app/layout.tsx
  one-day-hero/src/app/mission/create/layout.tsx
  one-day-hero/src/components/common/Footer.tsx
  one-day-hero/src/components/common/Header.tsx
  one-day-hero/src/components/common/HeroScore.tsx
  one-day-hero/src/components/common/HomeHeader.tsx
  one-day-hero/src/components/common/MissionProgressBar.tsx
Labels: Small Ticket, 기능

#57 컨테이너 컴포넌트 생성과 Daylist 컴포넌트 스타일 수정
  one-day-hero/src/app/(home)/page.tsx
  one-day-hero/src/components/common/Container.tsx
  one-day-hero/src/components/common/DayList.tsx
  one-day-hero/src/components/common/ToggleButton.tsx
Labels: Small Ticket

#61 홈페이지 미션 생성 버튼 생성
  one-day-hero/src/app/(home)/components/MissionCreateButton.tsx
  one-day-hero/src/app/(home)/layout.tsx
  one-day-hero/src/components/common/ToggleButton.tsx
Labels: Small Ticket

#63 tailwind config 수정합니다
  one-day-hero/src/app/layout.tsx
  one-day-hero/src/components/common/Footer.tsx
  one-day-hero/src/components/common/Header.tsx
  one-day-hero/src/components/common/HeroScore.tsx
  one-day-hero/src/components/common/HomeHeader.tsx
  one-day-hero/src/components/common/Label.tsx
  one-day-hero/src/components/common/ToggleButton.tsx
  one-day-hero/tailwind.config.ts
Labels: Small Ticket, 스타일

#64 refactor: 버튼 스타일 변경
  one-day-hero/src/components/common/Button.tsx
Labels: Small Ticket, 스타일

#66 mock 데이터 용 route handler 폴더 구조를 세팅합니다
  one-day-hero/src/app/api/mock/missions/route.ts
  one-day-hero/src/app/api/v1/mock/_data/mission/index.js
  one-day-hero/src/app/api/v1/mock/missions/[slug]/route.ts
  one-day-hero/src/app/api/v1/mock/missions/route.ts
  one-day-hero/src/app/mission/detail/[slug]/page.tsx
  one-day-hero/src/services/missions.ts
  one-day-hero/src/services/urls.ts
Labels: Small Ticket
