Repository prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE, pull requests merged in 2023-12, with the labels that each got.

#251 이미지 삭제 기능 추가
  one-day-hero/src/app/search/hero/page.tsx
  one-day-hero/src/components/common/Header.tsx
  one-day-hero/src/components/common/UploadImage.tsx
  one-day-hero/src/components/domain/chatting/ChatRoomItem.tsx
  one-day-hero/src/components/domain/review/ReviewForm.tsx
  one-day-hero/src/components/domain/review/ReviewInfo.tsx
  one-day-hero/src/components/domain/survey/MandatorySurvey.tsx
  one-day-hero/src/services/survey.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#257 미션 수정
  one-day-hero/src/app/api/editMission/[slug]/route.ts
  one-day-hero/src/app/heroProfile/[slug]/page.tsx
  one-day-hero/src/app/map/layout.tsx
  one-day-hero/src/app/map/page.tsx
  one-day-hero/src/app/mission/[slug]/(detail)/page.tsx
  one-day-hero/src/app/mission/[slug]/edit/layout.tsx
  one-day-hero/src/app/mission/[slug]/edit/page.tsx
  one-day-hero/src/app/mission/create/page.tsx
  one-day-hero/src/app/profile/page.tsx
  one-day-hero/src/components/domain/mission/create/CustomCalendar.tsx
  one-day-hero/src/components/domain/mission/create/MissionForm.tsx
  one-day-hero/src/components/domain/mission/create/PostCode.tsx
  one-day-hero/src/components/domain/missionDetail/CitizenInfo.tsx
  one-day-hero/src/components/domain/review/ReviewForm.tsx
  one-day-hero/src/components/domain/survey/MandatorySurvey.tsx
  one-day-hero/src/services/missions.ts
  one-day-hero/src/types/response.ts
  one-day-hero/src/types/schema.ts
Labels: Small Ticket, 기능

#264 제안받을 미션 heroId 추가
  one-day-hero/src/components/domain/mission/suggest/SuggestionForm.tsx
  one-day-hero/src/services/missions.ts
  one-day-hero/src/services/review.ts
Labels: Small Ticket, 기능

#259 px 단위 rem으로 변경
  one-day-hero/src/app/chatting/(list)/page.tsx
  one-day-hero/src/app/mission/[slug]/(detail)/page.tsx
  one-day-hero/src/components/common/Category.tsx
  one-day-hero/src/components/common/Info/MissionListItem.tsx
  one-day-hero/src/components/common/Input.tsx
  one-day-hero/src/components/common/Toast.tsx
  one-day-hero/src/components/common/UploadImage.tsx
  one-day-hero/src/components/domain/chatting/ChatRoomItem.tsx
  one-day-hero/src/components/domain/mission/create/PostCode.tsx
  one-day-hero/src/components/domain/review/ReviewInfo.tsx
  one-day-hero/src/components/domain/survey/MandatorySurvey.tsx
Labels: 스타일

#267 미션 생성시 잘못된 금액 에러 메세지 출력되는 이슈 해결
  one-day-hero/src/components/domain/mission/create/PostCode.tsx
Labels: Small Ticket, 기능

#260 QA 내역 핫픽스 3
  one-day-hero/src/app/chatting/[slug]/page.tsx
  one-day-hero/src/components/common/KebabMenu/KebabModal.tsx
  one-day-hero/src/components/domain/chatting/ChattingClientContainer.tsx
  one-day-hero/src/components/domain/chatting/ChattingInputFooter.tsx
Labels: Small Ticket, 기능

#269 채팅창 엔터 isComposing 처리 추가
  one-day-hero/src/components/common/FooterButton.tsx
  one-day-hero/src/components/common/Info/MissionListItem.tsx
  one-day-hero/src/components/common/MissionProgressContainer.tsx
  one-day-hero/src/components/domain/chatting/ChattingInputFooter.tsx
  one-day-hero/src/components/domain/mission/suggested/SuggestedMissionItem.tsx
Labels: Small Ticket, 기능

#271 레이아웃 핫 픽스 및 목록 아이템 찜 버튼 연결
  one-day-hero/src/app/chatting/[slug]/page.tsx
  one-day-hero/src/components/common/BookmarkButton.tsx
  one-day-hero/src/components/common/FooterButton.tsx
  one-day-hero/src/components/common/Info/MissionFullInfo.tsx
  one-day-hero/src/components/common/Info/MissionListItem.tsx
  one-day-hero/src/components/common/KebabMenu/KebabModal.tsx
  one-day-hero/src/components/domain/mission/ongoing/OngoingMissionList.tsx
  one-day-hero/src/components/domain/mission/suggest/SuggestionForm.tsx
  one-day-hero/src/components/domain/mission/suggested/SuggestedMissionItem.tsx
  one-day-hero/src/services/missions.ts
Labels: Small Ticket, 기능

#274 지도 이슈 해결
  one-day-hero/src/app/map/page.tsx
  one-day-hero/src/components/common/Select.tsx
  one-day-hero/src/components/domain/map/MapMissionList.tsx
  one-day-hero/src/services/map.ts
  one-day-hero/tailwind.config.ts
Labels: Small Ticket, 기능

#277 디자인 최종 수정
  one-day-hero/src/app/chatting/[slug]/layout.tsx
  one-day-hero/src/app/heroProfile/[slug]/page.tsx
  one-day-hero/src/app/mission/[slug]/(detail)/page.tsx
  one-day-hero/src/app/profile/page.tsx
  one-day-hero/src/components/common/Info/MissionListItem.tsx
  one-day-hero/src/components/common/NotificationCircle.tsx
  one-day-hero/src/components/common/ProfileImage.tsx
  one-day-hero/src/components/domain/chatting/ChatRoomItem.tsx
  one-day-hero/src/components/domain/chatting/Message.tsx
  one-day-hero/src/components/domain/chatting/MissionProgressButtonBar.tsx
  one-day-hero/src/components/domain/review/ReviewInfo.tsx
  one-day-hero/src/components/domain/survey/MandatorySurvey.tsx
  one-day-hero/src/components/domain/survey/OptionalSurvey.tsx
Labels: 스타일

#278 헤더 hover 시 색깔 및 푸터 버튼 수정
  one-day-hero/src/app/review/[slug]/(reviewId)/(detail)/page.tsx
  one-day-hero/src/components/common/FooterButton.tsx
  one-day-hero/src/components/domain/home/Banner.tsx
  one-day-hero/src/components/domain/home/HomeHeader.tsx
  one-day-hero/src/components/domain/review/ReviewInfo.tsx
Labels: Small Ticket, 스타일

#279 무한 스크롤 새로고침 기능 구현
  one-day-hero/src/app/chatting/(list)/page.tsx
  one-day-hero/src/app/search/hero/page.tsx
  one-day-hero/src/app/search/mission/page.tsx
  one-day-hero/src/components/common/BookmarkButton.tsx
  one-day-hero/src/components/common/Info/MissionFullInfo.tsx
  one-day-hero/src/components/common/Info/MissionListItem.tsx
  one-day-hero/src/components/common/NotificationCircle.tsx
  one-day-hero/src/components/domain/home/HomeMissionList.tsx
  one-day-hero/src/components/domain/mission/ongoing/OngoingMissionList.tsx
  one-day-hero/src/components/domain/mission/suggest/SuggestionForm.tsx
  one-day-hero/src/components/domain/mission/suggested/SuggestedMissionItem.tsx
  one-day-hero/src/components/domain/mission/suggested/SuggestedMissionList.tsx
  one-day-hero/src/components/domain/search/HeroSearch.tsx
  one-day-hero/src/components/domain/search/MissionSearch.tsx
  one-day-hero/src/hooks/useInfiniteFetch.ts
  one-day-hero/src/utils/storage.ts
Labels: Small Ticket, 기능

#284 배포 긴급 수정 내역 가져오기
  one-day-hero/src/app/(home)/page.tsx
  one-day-hero/src/app/favicon.ico
  one-day-hero/src/app/heroProfile/[slug]/page.tsx
  one-day-hero/src/app/layout.tsx
  one-day-hero/src/app/map/page.tsx
  one-day-hero/src/app/mission/list/layout.tsx
  one-day-hero/src/components/common/BookmarkButton.tsx
  one-day-hero/src/components/common/Category.tsx
  one-day-hero/src/components/domain/chatting/ChattingClientContainer.tsx
  one-day-hero/src/components/domain/map/MapMissionList.tsx
  one-day-hero/src/components/domain/mission/create/MissionForm.tsx
  one-day-hero/src/components/domain/search/HeroSearch.tsx
  one-day-hero/src/components/domain/search/MissionSearch.tsx
  one-day-hero/src/components/domain/survey/OptionalSurvey.tsx
Labels: 긴급

#286 배포 긴급 수정 내역 가져오기
  one-day-hero/src/app/(home)/page.tsx
  one-day-hero/src/app/favicon.ico
  one-day-hero/src/app/heroProfile/[slug]/page.tsx
  one-day-hero/src/app/layout.tsx
  one-day-hero/src/app/map/page.tsx
  one-day-hero/src/components/common/BookmarkButton.tsx
  one-day-hero/src/components/common/Category.tsx
  one-day-hero/src/components/domain/chatting/ChattingClientContainer.tsx
  one-day-hero/src/components/domain/map/MapMissionList.tsx
  one-day-hero/src/components/domain/mission/create/MissionForm.tsx
  one-day-hero/src/components/domain/search/HeroSearch.tsx
  one-day-hero/src/components/domain/search/MissionSearch.tsx
  one-day-hero/src/components/domain/survey/OptionalSurvey.tsx
Labels: Small Ticket, 긴급

#292 useDebounce hook 생성 및 오류 해결
  one-day-hero/src/app/search/hero/page.tsx
  one-day-hero/src/components/domain/search/HeroSearch.tsx
  one-day-hero/src/hooks/useDebounce.ts
Labels: 리팩토링

#293 next.js 14 및 관련 패키지 마이그레이션
  one-day-hero/package-lock.json
  one-day-hero/package.json
Labels: Small Ticket, 리팩토링
