Repository prgrms-web-devcourse/Team-6Heroes-OneDayHero-FE, pull requests merged in 2023-11, with the labels that each got.

#71 미션 이미지에 맞도록 스타일 수정
  one-day-hero/public/images/test.png
  one-day-hero/public/smiling-face.png
  one-day-hero/src/app/(home)/page.tsx
  one-day-hero/src/components/common/MissionListItem.tsx
Labels: Small Ticket, 스타일

#68 category 컴포넌트 구현
  one-day-hero/src/app/globals.css
  one-day-hero/src/app/mission/create/page.tsx
  one-day-hero/src/components/common/Category.tsx
  one-day-hero/src/components/common/HorizontalScroll.tsx
Labels: Small Ticket, 기능

#72 미션 목록 페이지 (진행중인 미션) 생성
  one-day-hero/package-lock.json
  one-day-hero/src/app/(home)/layout.tsx
  one-day-hero/src/app/mission/list/layout.tsx
  one-day-hero/src/app/mission/list/ongoing/page.tsx
  one-day-hero/src/app/mission/list/suggested/page.tsx
  one-day-hero/src/components/common/Container.tsx
  one-day-hero/src/components/common/Footer.tsx
  one-day-hero/src/components/common/Header.tsx
  one-day-hero/src/components/common/HomeHeader.tsx
  one-day-hero/src/components/common/MissionListItem.tsx
  one-day-hero/src/components/common/MissionProgressBar.tsx
  one-day-hero/src/components/common/MissionProgressContainer.tsx
  one-day-hero/src/components/common/Tabs.tsx
  one-day-hero/src/components/domain/home/MissionCreateButton.tsx
Labels: Small Ticket, 기능

#74 케밥 메뉴 버튼 및 연관 컴포넌트 생성합니다
  one-day-hero/src/app/mission/[slug]/layout.tsx
  one-day-hero/src/app/mission/[slug]/page.tsx
  one-day-hero/src/app/mission/detail/[slug]/page.tsx
  one-day-hero/src/components/common/KebabMenu/KebabModal.tsx
  one-day-hero/src/components/common/KebabMenu/MenuBox.tsx
  one-day-hero/src/components/common/KebabMenu/index.tsx
  one-day-hero/src/components/common/Modal.tsx
  one-day-hero/src/hooks/useModal.ts
Labels: Small Ticket, 기능

#79 전체 미션 정보 컴포넌트
  one-day-hero/src/app/(home)/page.tsx
  one-day-hero/src/app/mission/list/ongoing/page.tsx
  one-day-hero/src/app/mission/list/suggested/page.tsx
  one-day-hero/src/components/common/Header.tsx
  one-day-hero/src/components/common/Info/MissionFullInfo.tsx
  one-day-hero/src/components/common/Info/MissionInfo.tsx
  one-day-hero/src/components/common/Info/MissionListItem.tsx
Labels: Small Ticket, 기능

#77 헤더 컴포넌트 뒤로가기 기능 추가
  one-day-hero/src/components/common/BackButton.tsx
  one-day-hero/src/components/common/Header.tsx
Labels: Small Ticket, 기능

#81 미션 생성 Mock 데이터 테스트
  one-day-hero/src/app/api/v1/mock/missions/create/route.ts
  one-day-hero/src/app/mission/create/page.tsx
Labels: Small Ticket, 기능

#86 react-calendar 라이브러리 설치
  one-day-hero/package-lock.json
  one-day-hero/package.json
Labels: Small Ticket

#88 develop 에러 해결
  one-day-hero/src/app/mission/list/ongoing/page.tsx
  one-day-hero/src/app/mission/list/suggested/page.tsx
  one-day-hero/src/components/common/Info/MissionFullInfo.tsx
  one-day-hero/src/components/common/Info/MissionInfo.tsx
  one-day-hero/src/components/common/Info/MissionListItem.tsx
  one-day-hero/src/components/common/MissionListItem.tsx
Labels: Small Ticket, 긴급

#83 이미지 업로드 컴포넌트 구현
  one-day-hero/src/components/common/UploadImage.tsx
Labels: Small Ticket, 기능

#89 본인 시점 미션 상세 페이지 구현
  one-day-hero/public/images/OneDayHero_logo_sm.svg
  one-day-hero/src/app/api/v1/mock/_data/mission/index.js
  one-day-hero/src/app/api/v1/mock/_data/mission/index.ts
  one-day-hero/src/app/api/v1/mock/missions/[slug]/route.ts
  one-day-hero/src/app/mission/[slug]/layout.tsx
  one-day-hero/src/app/mission/[slug]/page.tsx
  one-day-hero/src/components/common/Header.tsx
  one-day-hero/src/components/common/KebabMenu/KebabModal.tsx
  one-day-hero/src/components/common/KebabMenu/MenuBox.tsx
  one-day-hero/src/components/common/KebabMenu/index.tsx
  one-day-hero/src/components/domain/missionDetail/HeroRecommendList.tsx
  one-day-hero/src/services/missions.ts
  one-day-hero/src/types/index.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#90 미션 목록 페이지(진행중인 미션) mock data를 이용한 api 작업
  one-day-hero/src/app/(home)/page.tsx
  one-day-hero/src/app/api/v1/mock/_data/mission/index.js
  one-day-hero/src/app/api/v1/mock/missions/list/ongoing/route.ts
  one-day-hero/src/app/mission/list/ongoing/page.tsx
  one-day-hero/src/components/common/IconGroup.tsx
  one-day-hero/src/components/common/Info/MissionListItem.tsx
  one-day-hero/src/components/common/MissionProgressBar.tsx
  one-day-hero/src/components/common/MissionProgressContainer.tsx
  one-day-hero/src/services/missions.ts
  one-day-hero/src/types/type.ts
Labels: Small Ticket, 기능

#92 미션 목록 페이지(제안받은 미션) mock data를 이용한 api 작업
  one-day-hero/src/app/api/v1/mock/_data/mission/index.js
  one-day-hero/src/app/api/v1/mock/missions/list/suggested/route.ts
  one-day-hero/src/app/mission/list/ongoing/page.tsx
  one-day-hero/src/app/mission/list/suggested/page.tsx
  one-day-hero/src/components/common/Button.tsx
  one-day-hero/src/components/common/Container.tsx
  one-day-hero/src/components/common/Info/MissionFullInfo.tsx
  one-day-hero/src/components/common/Info/MissionInfo.tsx
  one-day-hero/src/components/common/MissionProgressContainer.tsx
  one-day-hero/src/services/missions.ts
Labels: Small Ticket, 기능

#94 미션 생성 페이지
  one-day-hero/src/app/api/v1/mock/missions/create/route.ts
  one-day-hero/src/app/mission/create/layout.tsx
  one-day-hero/src/app/mission/create/page.tsx
  one-day-hero/src/components/common/Category.tsx
  one-day-hero/src/components/common/FooterButton.tsx
  one-day-hero/src/components/domain/mission/create/CreateForm.tsx
  one-day-hero/src/components/domain/mission/create/CustomCalendar.tsx
  one-day-hero/src/components/domain/mission/create/ErrorMessage.tsx
  one-day-hero/src/components/domain/mission/create/Input.tsx
  one-day-hero/src/components/domain/mission/create/InputLabel.tsx
  one-day-hero/src/components/domain/mission/create/Select.tsx
  one-day-hero/src/components/domain/mission/create/Textarea.tsx
  one-day-hero/src/constants/errorMessage.ts
  one-day-hero/src/hooks/useForm.ts
  one-day-hero/src/hooks/useFormValidation.ts
Labels: Small Ticket, 기능

#96 타인 시점 미션 상세페이지 구현
  one-day-hero/src/app/api/v1/mock/_data/mission/index.ts
  one-day-hero/src/app/api/v1/mock/_data/user/index.ts
  one-day-hero/src/app/api/v1/mock/bookmarks/route.ts
  one-day-hero/src/app/api/v1/mock/users/[slug]/route.ts
  one-day-hero/src/app/mission/[slug]/page.tsx
  one-day-hero/src/components/common/BookmarkButton.tsx
  one-day-hero/src/components/common/HeroScore.tsx
  one-day-hero/src/components/domain/missionDetail/CitizenInfo.tsx
  one-day-hero/src/services/missions.ts
  one-day-hero/src/services/users.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#99 미션 기록 페이지
  one-day-hero/src/app/api/v1/mock/_data/mission/index.js
  one-day-hero/src/app/api/v1/mock/missions/record/route.ts
  one-day-hero/src/app/mission/record/layout.tsx
  one-day-hero/src/app/mission/record/page.tsx
  one-day-hero/src/services/missions.ts
Labels: Small Ticket, 기능

#98 타인 프로필 페이지 구현
  one-day-hero/src/app/citizenProfile/[slug]/layout.tsx
  one-day-hero/src/app/citizenProfile/[slug]/page.tsx
  one-day-hero/src/app/heroProfile/[slug]/layout.tsx
  one-day-hero/src/app/heroProfile/[slug]/page.tsx
  one-day-hero/src/app/profile/layout.tsx
  one-day-hero/src/app/profile/page.tsx
  one-day-hero/src/components/common/FavoriteDateList.tsx
  one-day-hero/src/services/missions.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#101 빌드 오류 수정
  one-day-hero/.eslintrc.json
  one-day-hero/src/app/api/v1/mock/missions/route.ts
  one-day-hero/src/app/mission/create/page.tsx
  one-day-hero/src/services/missions.ts
Labels: 긴급

#104 미션 생성 페이지 코드 수정
  one-day-hero/src/app/mission/create/page.tsx
Labels: Small Ticket, 기능

#108 서비스 파일 형식 통일, 타입 파일 통합, mock 파일 통합
  one-day-hero/src/app/api/v1/mock/_data/mission/index.ts
  one-day-hero/src/services/missions.ts
  one-day-hero/src/types/response.ts
  one-day-hero/src/types/type.ts
Labels: 리팩토링

#111 develop branch merge 전 빌드 에러 수정
  one-day-hero/package-lock.json
  one-day-hero/package.json
  one-day-hero/src/app/api/v1/mock/_data/mission/index.ts
  one-day-hero/src/app/api/v1/mock/missions/[slug]/route.ts
  one-day-hero/src/app/api/v1/mock/missions/create/route.ts
  one-day-hero/src/app/api/v1/mock/users/[slug]/route.ts
  one-day-hero/src/app/chatting/[slug]/layout.tsx
  one-day-hero/src/app/citizenProfile/[slug]/page.tsx
  one-day-hero/src/app/heroProfile/[slug]/layout.tsx
  one-day-hero/src/app/heroProfile/[slug]/page.tsx
  one-day-hero/src/app/layout.tsx
  one-day-hero/src/app/mission/[slug]/page.tsx
  one-day-hero/src/app/mission/list/layout.tsx
  one-day-hero/src/app/mission/list/ongoing/page.tsx
  one-day-hero/src/app/mission/list/suggested/page.tsx
  one-day-hero/src/app/mission/record/page.tsx
  one-day-hero/src/app/profile/page.tsx
  one-day-hero/src/components/common/BookmarkButton.tsx
  one-day-hero/src/components/common/FavoriteDateList.tsx
  one-day-hero/src/components/common/Header.tsx
  one-day-hero/src/components/common/HeroScore.tsx
  one-day-hero/src/components/common/Info/MissionFullInfo.tsx
  one-day-hero/src/components/common/Info/MissionListItem.tsx
  one-day-hero/src/components/common/KebabMenu/KebabModal.tsx
  one-day-hero/src/components/common/KebabMenu/MenuBox.tsx
  one-day-hero/src/components/common/KebabMenu/index.tsx
  one-day-hero/src/components/common/MissionProgressContainer.tsx
  one-day-hero/src/components/common/Modal.tsx
  one-day-hero/src/components/domain/chatting/ChattingInputFooter.tsx
  one-day-hero/src/components/domain/mission/create/Input.tsx
  one-day-hero/src/components/domain/missionDetail/CitizenInfo.tsx
  one-day-hero/src/components/domain/missionDetail/HeroRecommendList.tsx
  one-day-hero/src/services/missions.ts
  one-day-hero/src/services/users.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 리팩토링

#112 로그인 페이지 UI 구현합니다
  one-day-hero/public/images/kakaoLogin 1.png
  one-day-hero/public/images/히어로 1.png
  one-day-hero/src/app/login/page.tsx
Labels: Small Ticket, 스타일

#113 알림 페이지 UI 구현
  one-day-hero/src/app/notification/layout.tsx
  one-day-hero/src/app/notification/page.tsx
  one-day-hero/src/app/utils/formatDate.ts
  one-day-hero/src/components/domain/notification/NotificationItem.tsx
Labels: Small Ticket, 스타일

#128 프로필 조사 폼필수 UI 구현
  one-day-hero/src/app/page.tsx
  one-day-hero/src/app/survey/layout.tsx
  one-day-hero/src/app/survey/mandatory/page.tsx
  one-day-hero/src/app/survey/optional/page.tsx
  one-day-hero/src/components/common/Textarea.tsx
  one-day-hero/src/components/domain/survey/MandatorySurvey.tsx
Labels: Small Ticket, 기능

#124 카카오 로그인 인가 과정 구현
  one-day-hero/package-lock.json
  one-day-hero/package.json
  one-day-hero/src/app/(home)/page.tsx
  one-day-hero/src/app/api/auth/[...nextauth]/authOptions.ts
  one-day-hero/src/app/api/auth/[...nextauth]/route.ts
  one-day-hero/src/app/layout.tsx
  one-day-hero/src/app/login/layout.tsx
  one-day-hero/src/app/login/page.tsx
  one-day-hero/src/app/mission/list/ongoing/page.tsx
  one-day-hero/src/app/oauth/[...slug]/page.tsx
  one-day-hero/src/components/common/Info/MissionListItem.tsx
  one-day-hero/src/components/common/Oauth/Providers.tsx
  one-day-hero/tsconfig.json
Labels: Small Ticket, 기능

#130 프로필 조사 폼 선택 페이지 UI 구현
  one-day-hero/src/app/survey/optional/page.tsx
  one-day-hero/src/components/domain/survey/OptionalSurvey.tsx
Labels: Small Ticket, 기능

#133 이미지 업로드 컴포넌트 삭제 기능 추가
  one-day-hero/package-lock.json
  one-day-hero/package.json
  one-day-hero/src/components/common/UploadImage.tsx
  one-day-hero/src/components/domain/mission/create/CreateForm.tsx
  one-day-hero/src/components/domain/review/ReviewForm.tsx
  one-day-hero/src/components/domain/survey/MandatorySurvey.tsx
  one-day-hero/src/types/index.ts
Labels: Small Ticket, 기능

#135 카테고리 미선택 시 에러메세지 버그 수정
  one-day-hero/src/components/common/Category.tsx
Labels: 긴급

#139 프로필 필수 조사 폼 클라이언트 단 내부 로직 구현
  one-day-hero/package.json
  one-day-hero/src/components/common/Input.tsx
  one-day-hero/src/components/domain/survey/MandatorySurvey.tsx
  one-day-hero/src/types/schema.ts
Labels: Small Ticket, 기능

#141 리뷰 수정 페이지 UI 구현
  one-day-hero/src/app/review/[slug]/edit/layout.tsx
  one-day-hero/src/app/review/[slug]/edit/page.tsx
  one-day-hero/src/components/domain/review/ReviewForm.tsx
Labels: Small Ticket, 기능

#144 useMutationalFetch 로직 수정 및 유저 정보 수정 Mock api 작성
  one-day-hero/src/app/api/v1/mock/_data/user/index.ts
  one-day-hero/src/app/api/v1/mock/me/route.ts
  one-day-hero/src/components/domain/survey/MandatorySurvey.tsx
  one-day-hero/src/services/base.ts
  one-day-hero/src/services/users.ts
  one-day-hero/src/types/index.ts
  one-day-hero/src/types/request.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#148 공용 toast 컴포넌트 구현
  one-day-hero/src/app/layout.tsx
  one-day-hero/src/components/common/Toast.tsx
  one-day-hero/src/components/common/UploadImage.tsx
  one-day-hero/src/contexts/ToastProvider.tsx
  one-day-hero/tailwind.config.ts
Labels: Small Ticket, 기능

#150 미션 생성 폼 데이터 수정
  one-day-hero/src/components/domain/mission/create/CreateForm.tsx
  one-day-hero/src/components/domain/mission/create/CustomCalendar.tsx
  one-day-hero/src/hooks/useFormValidation.ts
Labels: 긴급

#152 미션 생성 mock 구조 업데이트 및 프록시 설정
  one-day-hero/next.config.js
  one-day-hero/src/app/api/v1/mock/missions/create/route.ts
  one-day-hero/src/app/api/v1/mock/missions/route.ts
  one-day-hero/src/app/citizenProfile/[slug]/page.tsx
  one-day-hero/src/app/heroProfile/[slug]/page.tsx
  one-day-hero/src/app/mission/list/ongoing/page.tsx
  one-day-hero/src/app/profile/page.tsx
  one-day-hero/src/components/domain/mission/create/CreateForm.tsx
  one-day-hero/src/components/domain/mission/create/CustomCalendar.tsx
  one-day-hero/src/hooks/useFormValidation.ts
  one-day-hero/src/services/base.ts
  one-day-hero/src/services/missions.ts
  one-day-hero/src/services/users.ts
  one-day-hero/src/types/request.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#153 프로필 조사 폼선택 클라이언트 단 내부 로직
  one-day-hero/package-lock.json
  one-day-hero/src/app/api/v1/mock/_data/survey/index.ts
  one-day-hero/src/app/survey/category/page.tsx
  one-day-hero/src/components/common/DayList.tsx
  one-day-hero/src/components/common/Select.tsx
  one-day-hero/src/components/common/ToggleButton.tsx
  one-day-hero/src/components/domain/survey/MandatorySurvey.tsx
  one-day-hero/src/components/domain/survey/OptionalSurvey.tsx
  one-day-hero/src/types/response.ts
  one-day-hero/src/types/schema.ts
Labels: Small Ticket, 기능

#157 리뷰 인포 컴포넌트 생성
  one-day-hero/src/app/api/v1/mock/_data/review/index.ts
  one-day-hero/src/app/api/v1/mock/review/[slug]/[reviewId]/route.ts
  one-day-hero/src/app/review/[userId]/[reviewId]/layout.tsx
  one-day-hero/src/app/review/[userId]/[reviewId]/page.tsx
  one-day-hero/src/app/review/[userId]/edit/layout.tsx
  one-day-hero/src/app/review/[userId]/edit/page.tsx
  one-day-hero/src/app/review/[userId]/page.tsx
  one-day-hero/src/components/domain/mission/create/CreateForm.tsx
  one-day-hero/src/components/domain/review/ReviewInfo.tsx
  one-day-hero/src/services/review.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#160 제안받은 미션, 미션 기록, 선택 프로필 수정 페이지 mock 데이터 구조 업데이트
  one-day-hero/package-lock.json
  one-day-hero/src/app/api/v1/mock/_data/mission/index.ts
  one-day-hero/src/app/api/v1/mock/me/route.ts
  one-day-hero/src/app/api/v1/mock/mission-proposals/route.ts
  one-day-hero/src/app/api/v1/mock/missions/complete/[slug]/route.ts
  one-day-hero/src/app/api/v1/mock/missions/list/ongoing/route.ts
  one-day-hero/src/app/api/v1/mock/missions/route.ts
  one-day-hero/src/app/mission/list/ongoing/page.tsx
  one-day-hero/src/app/mission/list/suggested/page.tsx
  one-day-hero/src/app/mission/record/page.tsx
  one-day-hero/src/components/common/Button.tsx
  one-day-hero/src/components/common/DayList.tsx
  one-day-hero/src/components/common/Info/MissionFullInfo.tsx
  one-day-hero/src/components/common/ToggleButton.tsx
  one-day-hero/src/components/domain/survey/OptionalSurvey.tsx
  one-day-hero/src/services/missions.ts
  one-day-hero/src/types/response.ts
  one-day-hero/src/types/schema.ts
Labels: Small Ticket, 기능

#161 메인 홈페이지 구현
  one-day-hero/public/images/Banner3.png
  one-day-hero/public/images/img.jpg
  one-day-hero/public/images/토스트 UI.png
  one-day-hero/src/app/(home)/page.tsx
  one-day-hero/src/components/common/Category.tsx
  one-day-hero/src/components/common/HorizontalScroll.tsx
  one-day-hero/src/components/domain/home/Banner.tsx
  one-day-hero/src/components/domain/mission/create/CustomCalendar.tsx
  one-day-hero/src/components/domain/missionDetail/HeroRecommendList.tsx
  one-day-hero/src/config/assets.ts
Labels: Small Ticket, 기능

#170 로그인 및 쿠키 설정
  one-day-hero/next.config.js
  one-day-hero/package-lock.json
  one-day-hero/package.json
  one-day-hero/src/app/api/auth/[...nextauth]/authOptions.ts
  one-day-hero/src/app/api/auth/[...nextauth]/route.ts
  one-day-hero/src/app/api/token/route.ts
  one-day-hero/src/app/api/v1/mock/auth/kakao/login/route.ts
  one-day-hero/src/app/layout.tsx
  one-day-hero/src/app/login/layout.tsx
  one-day-hero/src/app/login/page.tsx
  one-day-hero/src/app/oauth/[...slug]/page.tsx
  one-day-hero/src/app/utils/auth.ts
  one-day-hero/src/app/utils/cookie.ts
  one-day-hero/src/components/common/Oauth/Providers.tsx
  one-day-hero/src/components/domain/mission/create/CreateForm.tsx
  one-day-hero/src/services/auth.ts
  one-day-hero/src/services/base.ts
  one-day-hero/src/services/missions.ts
  one-day-hero/src/services/users.ts
Labels: Small Ticket, 기능

#166 제안할 미션 고르기 페이지 구현
  one-day-hero/src/app/api/v1/mock/_data/mission/index.ts
  one-day-hero/src/app/api/v1/mock/me/[slug]/route.ts
  one-day-hero/src/app/api/v1/mock/mission-proposals/route.ts
  one-day-hero/src/app/api/v1/mock/missions/matching/[slug]/route.ts
  one-day-hero/src/app/citizenProfile/[slug]/layout.tsx
  one-day-hero/src/app/heroProfile/[slug]/layout.tsx
  one-day-hero/src/app/mission/suggest/[slug]/layout.tsx
  one-day-hero/src/app/mission/suggest/[slug]/page.tsx
  one-day-hero/src/components/common/FooterButton.tsx
  one-day-hero/src/components/domain/mission/suggest/SuggestionForm.tsx
  one-day-hero/src/services/missions.ts
  one-day-hero/src/types/request.ts
  one-day-hero/src/types/response.ts
  one-day-hero/src/types/schema.ts
Labels: Small Ticket, 기능

#167 미션 검색 페이지 UI 작업
  one-day-hero/src/app/search/hero/page.tsx
  one-day-hero/src/app/search/layout.tsx
  one-day-hero/src/app/search/mission/page.tsx
  one-day-hero/src/components/common/Select.tsx
  one-day-hero/src/components/domain/search/MissionSearchFilter.tsx
  one-day-hero/src/components/domain/survey/OptionalSurvey.tsx
Labels: Small Ticket, 기능

#177 무한 스크롤 수정
  one-day-hero/src/app/api/v1/mock/_data/mission/index.ts
  one-day-hero/src/app/api/v1/mock/mission-proposals/route.ts
  one-day-hero/src/app/api/v1/mock/missions/complete/[slug]/route.ts
  one-day-hero/src/app/api/v1/mock/missions/progress/[slug]/route.ts
  one-day-hero/src/app/heroProfile/[slug]/page.tsx
  one-day-hero/src/app/mission/list/ongoing/page.tsx
  one-day-hero/src/app/mission/list/suggested/page.tsx
  one-day-hero/src/app/mission/record/page.tsx
  one-day-hero/src/app/mission/suggest/[slug]/page.tsx
  one-day-hero/src/app/profile/page.tsx
  one-day-hero/src/app/utils/cookie.ts
  one-day-hero/src/components/domain/mission/ongoing/OngoingMissionList.tsx
  one-day-hero/src/components/domain/mission/record/RecordMissionList.tsx
  one-day-hero/src/components/domain/mission/suggest/SuggestionForm.tsx
  one-day-hero/src/components/domain/mission/suggested/SuggestedMissionList.tsx
  one-day-hero/src/hooks/useInfiniteFetch.ts
  one-day-hero/src/services/base.ts
  one-day-hero/src/services/missions.ts
  one-day-hero/src/services/users.ts
Labels: Small Ticket, 기능

#180 프로필 페이지들 데이터 업데이트
  one-day-hero/src/app/api/v1/mock/_data/user/index.ts
  one-day-hero/src/app/citizenProfile/[slug]/page.tsx
  one-day-hero/src/app/heroProfile/[slug]/page.tsx
  one-day-hero/src/app/profile/page.tsx
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#182 필수와 선택 조사 페이지 api 연결 로직 재설정
  one-day-hero/src/app/api/createMandatorySurvey/route.ts
  one-day-hero/src/app/api/createOptionalSurvey/route.ts
  one-day-hero/src/app/heroProfile/[slug]/page.tsx
  one-day-hero/src/app/survey/mandatory/page.tsx
  one-day-hero/src/app/survey/optional/page.tsx
  one-day-hero/src/components/common/UploadImage.tsx
  one-day-hero/src/components/domain/mission/create/CreateForm.tsx
  one-day-hero/src/components/domain/review/ReviewForm.tsx
  one-day-hero/src/components/domain/survey/MandatorySurvey.tsx
  one-day-hero/src/components/domain/survey/OptionalSurvey.tsx
  one-day-hero/src/types/response.ts
  one-day-hero/src/types/schema.ts
Labels: Small Ticket, 기능, 긴급

#188 userId context 생성
  one-day-hero/src/app/api/token/route.ts
  one-day-hero/src/app/layout.tsx
  one-day-hero/src/app/oauth/[...slug]/page.tsx
  one-day-hero/src/contexts/UserIdProvider.tsx
Labels: Small Ticket, 기능

#184 formdata post 요청 수정
  one-day-hero/src/app/api/createPost/route.ts
  one-day-hero/src/app/api/createReview/route.ts
  one-day-hero/src/components/domain/mission/create/CreateForm.tsx
  one-day-hero/src/components/domain/review/ReviewForm.tsx
  one-day-hero/src/services/review.ts
  one-day-hero/src/types/schema.ts
Labels: Small Ticket, 기능

#174 히어로 검색 페이지 UI 구현
  one-day-hero/src/app/search/hero/layout.tsx
  one-day-hero/src/app/search/hero/page.tsx
  one-day-hero/src/app/search/mission/layout.tsx
  one-day-hero/src/components/common/Category.tsx
  one-day-hero/src/types/schema.ts
Labels: Small Ticket, 스타일

#172 미션 검색 페이지 기능 구현
  one-day-hero/src/app/(home)/layout.tsx
  one-day-hero/src/app/api/v1/mock/_data/search/index.ts
  one-day-hero/src/app/layout.tsx
  one-day-hero/src/app/mission/create/page.tsx
  one-day-hero/src/components/common/Category.tsx
  one-day-hero/src/components/common/Select.tsx
  one-day-hero/src/components/domain/home/HomeHeader.tsx
  one-day-hero/src/components/domain/mission/create/CreateForm.tsx
  one-day-hero/src/services/search.ts
Labels: Small Ticket, 기능, 스타일

#189 무한 스크롤 훅 연결 및 미션 검색 페이지 대규모 수정
  one-day-hero/src/app/search/mission/page.tsx
  one-day-hero/src/components/common/Category.tsx
  one-day-hero/src/components/domain/mission/suggested/SuggestedMissionList.tsx
  one-day-hero/src/hooks/useInfiniteFetch.ts
  one-day-hero/src/services/missions.ts
  one-day-hero/src/services/regions.ts
  one-day-hero/src/services/search.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#194 히어로 검색 페이지 기능 구현
  one-day-hero/src/app/search/hero/page.tsx
  one-day-hero/src/app/search/layout.tsx
  one-day-hero/src/hooks/useInfiniteFetch.ts
  one-day-hero/src/services/search.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능, 스타일

#199 조사 페이지 이미지 포함 post 요청 작업 및 지역 정보 데이터 구조 변경 반영
  one-day-hero/src/app/api/createMandatorySurvey/route.ts
  one-day-hero/src/app/api/createOptionalSurvey/route.ts
  one-day-hero/src/app/search/mission/page.tsx
  one-day-hero/src/app/survey/mandatory/page.tsx
  one-day-hero/src/app/survey/optional/page.tsx
  one-day-hero/src/components/domain/survey/MandatorySurvey.tsx
  one-day-hero/src/components/domain/survey/OptionalSurvey.tsx
  one-day-hero/src/services/search.ts
  one-day-hero/src/types/response.ts
  one-day-hero/src/types/schema.ts
Labels: Small Ticket, 기능

#191 채팅 페이지 UI 및 메시지 기능 구현 1
  one-day-hero/package-lock.json
  one-day-hero/package.json
  one-day-hero/src/app/api/v1/mock/_data/chatting/index.ts
  one-day-hero/src/app/api/v1/mock/chat-rooms/users/route.ts
  one-day-hero/src/app/api/v1/mock/mission-proposals/route.ts
  one-day-hero/src/app/chatting/(list)/layout.tsx
  one-day-hero/src/app/chatting/(list)/page.tsx
  one-day-hero/src/app/chatting/[slug]/layout.tsx
  one-day-hero/src/app/chatting/[slug]/page.tsx
  one-day-hero/src/app/heroProfile/[slug]/page.tsx
  one-day-hero/src/app/oauth/[...slug]/page.tsx
  one-day-hero/src/components/common/Footer.tsx
  one-day-hero/src/components/common/ProfileImage.tsx
  one-day-hero/src/components/domain/chatting/ChatRoomItem.tsx
  one-day-hero/src/components/domain/chatting/ChattingClientContainer.tsx
  one-day-hero/src/components/domain/chatting/ChattingInputFooter.tsx
  one-day-hero/src/components/domain/chatting/Message.tsx
  one-day-hero/src/components/domain/chatting/MessageContainer.tsx
  one-day-hero/src/components/domain/profile/FavoriteDateList.tsx
  one-day-hero/src/contexts/UserIdProvider.tsx
  one-day-hero/src/hooks/useChatting.ts
  one-day-hero/src/services/chats.ts
  one-day-hero/src/types/index.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#195 채팅 페이지 UI 및 메시지 기능 구현 2
  one-day-hero/src/app/api/token/route.ts
  one-day-hero/src/app/api/v1/mock/_data/chatting/index.ts
  one-day-hero/src/app/chatting/(list)/page.tsx
  one-day-hero/src/app/chatting/[slug]/layout.tsx
  one-day-hero/src/app/chatting/[slug]/page.tsx
  one-day-hero/src/app/mission/[slug]/page.tsx
  one-day-hero/src/app/utils/auth.ts
  one-day-hero/src/app/utils/formatTime.ts
  one-day-hero/src/components/common/KebabMenu/KebabModal.tsx
  one-day-hero/src/components/domain/chatting/ChatRoomItem.tsx
  one-day-hero/src/components/domain/chatting/ChattingClientContainer.tsx
  one-day-hero/src/components/domain/chatting/Message.tsx
  one-day-hero/src/components/domain/chatting/MessageContainer.tsx
  one-day-hero/src/components/domain/chatting/MissionProgressButtonBar.tsx
  one-day-hero/src/components/domain/missionDetail/CitizenInfo.tsx
  one-day-hero/src/hooks/useChatting.ts
  one-day-hero/src/services/chats.ts
  one-day-hero/src/services/missions.ts
  one-day-hero/src/services/users.ts
  one-day-hero/src/types/index.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#197 메인페이지 api 연결과 사용자 위치정보 받아오기
  one-day-hero/package-lock.json
  one-day-hero/package.json
  one-day-hero/src/app/(home)/page.tsx
  one-day-hero/src/app/layout.tsx
  one-day-hero/src/app/notification/page.tsx
  one-day-hero/src/components/common/Footer.tsx
  one-day-hero/src/components/common/NotificationCircle.tsx
  one-day-hero/src/components/domain/home/HomeHeader.tsx
  one-day-hero/src/components/domain/home/HomeLocation.tsx
  one-day-hero/src/contexts/NotificationProvider.tsx
  one-day-hero/src/hooks/useLocation.ts
  one-day-hero/src/services/home.ts
  one-day-hero/src/services/notification.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#202 api 정보 업데이트 및 오류 수정
  one-day-hero/src/app/(home)/layout.tsx
  one-day-hero/src/app/(home)/page.tsx
  one-day-hero/src/app/api/createMandatorySurvey/route.ts
  one-day-hero/src/app/api/v1/mock/_data/mission/index.ts
  one-day-hero/src/app/chatting/[slug]/layout.tsx
  one-day-hero/src/app/citizenProfile/[slug]/page.tsx
  one-day-hero/src/app/heroProfile/[slug]/page.tsx
  one-day-hero/src/app/mission/[slug]/layout.tsx
  one-day-hero/src/app/mission/[slug]/page.tsx
  one-day-hero/src/app/mission/create/page.tsx
  one-day-hero/src/app/mission/suggest/[slug]/page.tsx
  one-day-hero/src/app/profile/page.tsx
  one-day-hero/src/app/review/[userId]/[reviewId]/layout.tsx
  one-day-hero/src/app/search/hero/page.tsx
  one-day-hero/src/components/common/Info/MissionFullInfo.tsx
  one-day-hero/src/components/common/Info/MissionListItem.tsx
  one-day-hero/src/components/common/KebabMenu/KebabModal.tsx
  one-day-hero/src/components/domain/chatting/MissionProgressButtonBar.tsx
  one-day-hero/src/components/domain/home/HomeHeader.tsx
  one-day-hero/src/components/domain/mission/create/CreateForm.tsx
  one-day-hero/src/components/domain/mission/suggest/SuggestionForm.tsx
  one-day-hero/src/components/domain/mission/suggested/SuggestedMissionItem.tsx
  one-day-hero/src/components/domain/mission/suggested/SuggestedMissionList.tsx
  one-day-hero/src/components/domain/missionDetail/ChattingButton.tsx
  one-day-hero/src/components/domain/profile/HeroSwitch.tsx
  one-day-hero/src/contexts/NotificationProvider.tsx
  one-day-hero/src/services/base.ts
  one-day-hero/src/services/chats.ts
  one-day-hero/src/services/missions.ts
  one-day-hero/src/services/review.ts
  one-day-hero/src/services/search.ts
  one-day-hero/src/services/users.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#205 로그인 페이지 디자인 수정
  one-day-hero/public/images/textlogo.png
  one-day-hero/public/images/텍스트로고.png
  one-day-hero/src/app/login/layout.tsx
  one-day-hero/src/app/login/page.tsx
Labels: 스타일

#207 선택 조사 페이지 토스트 적용
  one-day-hero/src/components/domain/survey/OptionalSurvey.tsx
Labels: 기능

#210 로그인 redirect 처리
  one-day-hero/src/app/oauth/[...slug]/page.tsx
Labels: Small Ticket, 기능

#212 미션 검색 페이지 리팩토링
  one-day-hero/src/app/search/mission/page.tsx
  one-day-hero/src/components/common/Category.tsx
  one-day-hero/src/components/common/Info/MissionListItem.tsx
  one-day-hero/src/components/common/Label.tsx
Labels: Small Ticket, 기능, 스타일

#221 로딩 글자 크기 조정
  one-day-hero/src/app/oauth/[...slug]/page.tsx
Labels: 스타일

#220 알림
  one-day-hero/src/app/notification/page.tsx
  one-day-hero/src/components/domain/home/HomeHeader.tsx
  one-day-hero/src/components/domain/notification/NotificationItem.tsx
  one-day-hero/src/contexts/NotificationProvider.tsx
  one-day-hero/src/services/notification.ts
Labels: Small Ticket, 기능

#225 빌드 에러 수정
  one-day-hero/src/app/api/v1/mock/_data/mission/index.ts
  one-day-hero/src/app/api/v1/mock/_data/review/index.ts
  one-day-hero/src/app/api/v1/mock/_data/search/index.ts
  one-day-hero/src/app/api/v1/mock/_data/survey/index.ts
  one-day-hero/src/components/domain/search/MissionSearchFilter.tsx
  one-day-hero/src/contexts/NotificationProvider.tsx
Labels: Small Ticket, 기능

#229 메인 머지 충돌 해결
  one-day-hero/package-lock.json
  one-day-hero/src/app/layout.tsx
  one-day-hero/src/components/common/Info/MissionListItem.tsx
  one-day-hero/src/components/domain/missionDetail/HeroRecommendList.tsx
Labels: Small Ticket, 긴급

#228 지도 페이지 구현
  one-day-hero/package-lock.json
  one-day-hero/package.json
  one-day-hero/src/app/layout.tsx
  one-day-hero/src/app/map/layout.tsx
  one-day-hero/src/app/map/page.tsx
  one-day-hero/src/app/mission/[slug]/(detail)/page.tsx
  one-day-hero/src/components/common/FooterButton.tsx
  one-day-hero/src/components/common/NotificationCircle.tsx
  one-day-hero/src/components/domain/home/HomeLocation.tsx
  one-day-hero/src/components/domain/map/MapMissionList.tsx
  one-day-hero/src/components/domain/mission/create/CreateForm.tsx
  one-day-hero/src/components/domain/mission/create/PostCode.tsx
  one-day-hero/src/hooks/useLocation.ts
  one-day-hero/src/services/map.ts
  one-day-hero/src/types/index.ts
  one-day-hero/src/types/request.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#231 빌드에러 수정 및 알람 비활성화
  one-day-hero/package-lock.json
  one-day-hero/src/app/api/v1/mock/_data/mission/index.ts
  one-day-hero/src/app/notification/page.tsx
  one-day-hero/src/app/search/mission/page.tsx
  one-day-hero/src/components/common/Info/MissionFullInfo.tsx
  one-day-hero/src/components/domain/chatting/ChattingClientContainer.tsx
  one-day-hero/src/components/domain/mission/suggest/SuggestionForm.tsx
  one-day-hero/src/components/domain/mission/suggested/SuggestedMissionItem.tsx
Labels: Small Ticket, 긴급

#236 QA 간단 수정 사항 반영
  one-day-hero/src/app/api/token/route.ts
  one-day-hero/src/app/api/v1/mock/_data/mission/index.ts
  one-day-hero/src/app/chatting/[slug]/layout.tsx
  one-day-hero/src/app/mission/[slug]/(detail)/page.tsx
  one-day-hero/src/app/profile/page.tsx
  one-day-hero/src/app/search/mission/page.tsx
  one-day-hero/src/components/common/BookmarkButton.tsx
  one-day-hero/src/components/common/Info/MissionFullInfo.tsx
  one-day-hero/src/components/domain/chatting/ChatRoomItem.tsx
  one-day-hero/src/components/domain/mission/ongoing/OngoingMissionList.tsx
  one-day-hero/src/components/domain/missionDetail/CitizenInfo.tsx
  one-day-hero/src/components/domain/review/ReviewForm.tsx
  one-day-hero/src/services/chats.ts
  one-day-hero/src/services/missions.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#238 리뷰 수정 중 이미지 삭제 api 연결
  one-day-hero/src/components/common/UploadImage.tsx
  one-day-hero/src/components/domain/review/ReviewForm.tsx
  one-day-hero/src/services/review.ts
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#235 선택 조사 페이지 프로필 수정으로 접근했을때 기본값 처리
  one-day-hero/src/app/notification/page.tsx
  one-day-hero/src/components/common/DayList.tsx
  one-day-hero/src/components/common/Select.tsx
  one-day-hero/src/components/common/ToggleButton.tsx
  one-day-hero/src/components/domain/survey/OptionalSurvey.tsx
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#243 알림 이슈 처리
  one-day-hero/src/app/layout.tsx
  one-day-hero/src/app/notification/page.tsx
  one-day-hero/src/app/utils/storage.ts
  one-day-hero/src/components/common/NotificationCircle.tsx
  one-day-hero/src/components/domain/notification/NotificationItem.tsx
  one-day-hero/src/contexts/NotificationProvider.tsx
Labels: Small Ticket, 기능

#244 캐시 처리 및 핫 픽스 2
  one-day-hero/src/app/api/createMandatorySurvey/route.ts
  one-day-hero/src/app/api/createOptionalSurvey/route.ts
  one-day-hero/src/app/api/createPost/route.ts
  one-day-hero/src/app/api/createReview/route.ts
  one-day-hero/src/app/api/editReview/[slug]/route.ts
  one-day-hero/src/app/api/revalidateTag/route.ts
  one-day-hero/src/app/api/token/route.ts
  one-day-hero/src/app/chatting/[slug]/layout.tsx
  one-day-hero/src/app/chatting/[slug]/page.tsx
  one-day-hero/src/app/citizenProfile/[slug]/page.tsx
  one-day-hero/src/app/heroProfile/[slug]/page.tsx
  one-day-hero/src/app/profile/page.tsx
  one-day-hero/src/app/search/mission/page.tsx
  one-day-hero/src/components/common/KebabMenu/KebabModal.tsx
  one-day-hero/src/components/common/Tabs.tsx
  one-day-hero/src/components/domain/chatting/MissionProgressButtonBar.tsx
  one-day-hero/src/components/domain/mission/create/CreateForm.tsx
  one-day-hero/src/components/domain/review/ReviewForm.tsx
  one-day-hero/src/components/domain/survey/MandatorySurvey.tsx
  one-day-hero/src/components/domain/survey/OptionalSurvey.tsx
  one-day-hero/src/services/base.ts
  one-day-hero/src/services/map.ts
  one-day-hero/src/services/missions.ts
  one-day-hero/src/services/notification.ts
  one-day-hero/src/services/review.ts
  one-day-hero/src/services/search.ts
  one-day-hero/src/services/users.ts
  one-day-hero/src/types/index.ts
Labels: Small Ticket, 기능

#246 핫 픽스 3
  one-day-hero/src/app/notification/page.tsx
  one-day-hero/src/components/domain/survey/OptionalSurvey.tsx
  one-day-hero/src/types/response.ts
Labels: Small Ticket, 기능

#250 usefetch 이름 수정, usemutationalfetch 에 loading 추가 및 중복 클릭 방지
  one-day-hero/src/app/api/createMandatorySurvey/route.ts
  one-day-hero/src/app/api/createMission/route.ts
  one-day-hero/src/app/api/createReview/route.ts
  one-day-hero/src/app/api/editProfile/route.ts
  one-day-hero/src/app/api/editReview/[slug]/route.ts
  one-day-hero/src/app/api/token/route.ts
  one-day-hero/src/app/chatting/(list)/page.tsx
  one-day-hero/src/app/chatting/[slug]/layout.tsx
  one-day-hero/src/app/chatting/[slug]/page.tsx
  one-day-hero/src/app/citizenProfile/[slug]/page.tsx
  one-day-hero/src/app/heroProfile/[slug]/page.tsx
  one-day-hero/src/app/map/layout.tsx
  one-day-hero/src/app/map/page.tsx
  one-day-hero/src/app/mission/[slug]/(detail)/layout.tsx
  one-day-hero/src/app/mission/[slug]/(detail)/page.tsx
  one-day-hero/src/app/mission/[slug]/review/page.tsx
  one-day-hero/src/app/mission/list/layout.tsx
  one-day-hero/src/app/mission/suggest/[slug]/page.tsx
  one-day-hero/src/app/profile/page.tsx
  one-day-hero/src/app/review/[slug]/(reviewId)/(detail)/layout.tsx
  one-day-hero/src/app/review/[slug]/(reviewId)/(detail)/page.tsx
  one-day-hero/src/app/search/layout.tsx
  one-day-hero/src/app/search/mission/page.tsx
  one-day-hero/src/app/survey/mandatory/page.tsx
  one-day-hero/src/app/survey/optional/page.tsx
  one-day-hero/src/components/common/BackButton.tsx
  one-day-hero/src/components/common/BookmarkButton.tsx
  one-day-hero/src/components/common/KebabMenu/KebabModal.tsx
  one-day-hero/src/components/common/UploadImage.tsx
  one-day-hero/src/components/domain/chatting/ChattingClientContainer.tsx
  one-day-hero/src/components/domain/home/HomeMissionList.tsx
  one-day-hero/src/components/domain/mission/create/CreateForm.tsx
  one-day-hero/src/components/domain/mission/record/RecordMissionList.tsx
  one-day-hero/src/components/domain/mission/suggested/SuggestedMissionItem.tsx
  one-day-hero/src/components/domain/missionDetail/CitizenInfo.tsx
  one-day-hero/src/components/domain/profile/HeroSwitch.tsx
  one-day-hero/src/components/domain/review/ReceivedReviewList.tsx
  one-day-hero/src/components/domain/review/ReviewForm.tsx
  one-day-hero/src/components/domain/review/SentReviewList.tsx
  one-day-hero/src/components/domain/survey/MandatorySurvey.tsx
  one-day-hero/src/components/domain/survey/OptionalSurvey.tsx
  one-day-hero/src/contexts/UserIdProvider.tsx
  one-day-hero/src/hooks/useInfiniteFetch.ts
  one-day-hero/src/hooks/useMutationalFetch.ts
  one-day-hero/src/services/auth.ts
  one-day-hero/src/services/base.ts
  one-day-hero/src/services/chats.ts
  one-day-hero/src/services/home.ts
  one-day-hero/src/services/map.ts
  one-day-hero/src/services/missions.ts
  one-day-hero/src/services/notification.ts
  one-day-hero/src/services/regions.ts
  one-day-hero/src/services/review.ts
  one-day-hero/src/services/search.ts
  one-day-hero/src/services/users.ts
  one-day-hero/src/types/response.ts
  one-day-hero/src/utils/storage.ts
Labels: Small Ticket, 기능
